// Generated by nitro

// App Config
import type { Defu } from 'defu'

import type { default as appConfig0 } from "/Users/jiyankang/vscodeProjects/witque-blog/.starters/default/app.config";
import type { default as appConfig1 } from "/Users/jiyankang/vscodeProjects/witque-blog/app.config";
import type { default as appConfig2 } from "/Users/jiyankang/vscodeProjects/witque-blog/node_modules/.pnpm/@nuxt-themes+typography@0.11.0_rollup@3.29.3_vue@3.4.15/node_modules/@nuxt-themes/typography/app.config";
import type { default as appConfig3 } from "/Users/jiyankang/vscodeProjects/witque-blog/node_modules/.pnpm/@nuxt-themes+elements@0.9.5_rollup@3.29.3_vue@3.4.15/node_modules/@nuxt-themes/elements/app.config";

type UserAppConfig = Defu<{}, [typeof appConfig0, typeof appConfig1, typeof appConfig2, typeof appConfig3]>

declare module 'nitropack' {
  interface AppConfig extends UserAppConfig {}
}
    
export {}